CREATE TABLE dbfs_files (
    itemid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    fsid INTEGER NOT NULL,
    tagid TEXT COLLATE NOCASE,
    filetype INTEGER DEFAULT 0 NOT NULL,
    anchor INTEGER DEFAULT 0 NOT NULL UNIQUE,
    parentid INTEGER NOT NULL,
    name TEXT NOT NULL COLLATE NOCASE,
    size INTEGER DEFAULT 0 NOT NULL,
    ctime INTEGER DEFAULT 0 NOT NULL,
    mtime INTEGER DEFAULT 0 NOT NULL,
    tombstoned INTEGER DEFAULT 0 NOT NULL,
    uti TEXT NOT NULL COLLATE NOCASE,
    state_flags INTEGER DEFAULT 0 NOT NULL,
    error_code INTEGER DEFAULT 0 NOT NULL
);

-- Create the general state table
CREATE TABLE dbfs_dbstate (
    name TEXT PRIMARY KEY,
    value INTEGER UNIQUE
) WITHOUT ROWID;

